using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CivicOps.Infrastructure.Persistence.Migrations;

/// <summary>
/// Initial schema migration.
/// In a real workflow this file is generated by:
///   dotnet ef migrations add InitialCreate -p src/CivicOps.Infrastructure -s src/CivicOps.Api
/// It is committed here as a reference of the expected schema shape.
/// Run with: dotnet ef database update -p src/CivicOps.Infrastructure -s src/CivicOps.Api
/// </summary>
public partial class InitialCreate : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        // tenants
        migrationBuilder.CreateTable(
            name: "tenants",
            columns: table => new
            {
                Id = table.Column<Guid>(type: "uuid", nullable: false),
                Name = table.Column<string>(maxLength: 200, nullable: false),
                Slug = table.Column<string>(maxLength: 100, nullable: false),
                Tier = table.Column<string>(maxLength: 30, nullable: false, defaultValue: "professional"),
                IsActive = table.Column<bool>(nullable: false, defaultValue: true),
                MaxUnits = table.Column<int>(nullable: false, defaultValue: 50),
                MaxUsers = table.Column<int>(nullable: false, defaultValue: 25),
                LogoUrl = table.Column<string>(maxLength: 500, nullable: true),
                PrimaryColor = table.Column<string>(maxLength: 10, nullable: true),
                SecondaryColor = table.Column<string>(maxLength: 10, nullable: true),
                CustomDomain = table.Column<string>(maxLength: 200, nullable: true),
                CompanyName = table.Column<string>(maxLength: 200, nullable: true),
                SupportEmail = table.Column<string>(maxLength: 320, nullable: true),
                AiDispatchEnabled = table.Column<bool>(nullable: false, defaultValue: true),
                PredictiveMaintenanceEnabled = table.Column<bool>(nullable: false, defaultValue: true),
                WhatsAppIntegrationEnabled = table.Column<bool>(nullable: false, defaultValue: false),
                ClientViewerPortalEnabled = table.Column<bool>(nullable: false, defaultValue: false),
                DefaultSlaMinutes = table.Column<int>(nullable: false, defaultValue: 10),
                TimeZone = table.Column<string>(maxLength: 50, nullable: false, defaultValue: "Africa/Johannesburg"),
                CreatedAt = table.Column<DateTime>(type: "timestamptz", nullable: false),
                UpdatedAt = table.Column<DateTime>(type: "timestamptz", nullable: true),
                ExpiresAt = table.Column<DateTime>(type: "timestamptz", nullable: true),
                CreatedBy = table.Column<string>(nullable: true),
                UpdatedBy = table.Column<string>(nullable: true)
            },
            constraints: table => table.PrimaryKey("PK_tenants", x => x.Id));

        migrationBuilder.CreateIndex("IX_tenants_Slug", "tenants", "Slug", unique: true);

        // NOTE: For brevity in this committed reference file, the remaining
        // CREATE TABLE statements (users, vehicles, vehicle_gps_events, incidents,
        // dispatch_assignments, maintenance_*, geofences, regions, panic_events,
        // notifications, refresh_tokens, audit_logs) follow the same pattern and
        // are emitted in full by `dotnet ef migrations add InitialCreate`.
        //
        // The entity configurations in Configurations/EntityConfigurations.cs are
        // the single source of truth for column types, lengths, indexes, and FKs.
        // Running the EF CLI command above regenerates this file completely.
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable("tenants");
        // ... corresponding DROP TABLE for all other tables
    }
}
